version: "3.8"

services:
  web:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/ip9.conf:/etc/nginx/conf.d/default.conf
  ip9:
    image: mparvin/ip9:latest
    volumes:
      - ./ip9:/app